### ISSUE TITLE
Unable to build in hyprland 0.53

### ISSUE THREAD

**Issue by sdooweloc** [shezdy/hyprsplit#68]
Error when trying to build on hyprland 0.53

```
→ Building hyprsplit
 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╍━━━━━━━━━━━━━━━━━━━  3 / 5  Building plugin(s)[v] shell returned:  -> cd /run/user/1000/hyprpm/sdooweloc && PKG_CONFIG_PATH="/var/cache/hyprpm/sdooweloc/headersRoot/share/pkgconfig" make all
g++ -shared -fPIC --no-gnu-unique -Wall -g -DWLR_USE_UNSTABLE -std=c++23 -O2 `pkg-config --cflags pixman-1 libdrm hyprland` src/main.cpp -o hyprsplit.so
In file included from /usr/include/c++/15.2.1/chrono:51,
                 from /var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/managers/eventLoop/EventLoopTimer.hpp:3,
                 from /var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/managers/KeybindManager.hpp:10,
                 from /var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/Compositor.hpp:8,
                 from src/main.cpp:8:
/usr/include/c++/15.2.1/sstream:462:7: error: ‘struct std::__cxx11::basic_stringbuf<_CharT, _Traits, _Alloc>::__xfer_bufptrs’ redeclared with different access [-Wtemplate-body]
  462 |       struct __xfer_bufptrs
      |       ^~~~~~
src/main.cpp: In function ‘std::string getWorkspaceOnCurrentMonitor(const std::string&)’:
src/main.cpp:21:25: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
   21 |     if (!g_pCompositor->m_lastMonitor) {
      |                         ^~~~~~~~~~~~~
src/main.cpp:22:9: error: ‘Debug’ has not been declared
   22 |         Debug::log(ERR, "[hyprsplit] no monitor in getWorkspaceOnCurrentMonitor?");
      |         ^~~~~
src/main.cpp:22:20: error: ‘ERR’ was not declared in this scope; did you mean ‘Log::ERR’?
   22 |         Debug::log(ERR, "[hyprsplit] no monitor in getWorkspaceOnCurrentMonitor?");
      |                    ^~~
      |                    Log::ERR
In file included from /var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/plugins/../helpers/../macros.hpp:9,
                 from /var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/plugins/../helpers/Color.hpp:5,
                 from /var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/plugins/PluginAPI.hpp:23,
                 from src/globals.hpp:3,
                 from src/main.cpp:1:
/var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/plugins/../helpers/../debug/log/Logger.hpp:57:54: note: ‘Log::ERR’ declared here
   57 |     inline constexpr const Hyprutils::CLI::eLogLevel ERR   = Hyprutils::CLI::LOG_ERR;
      |                                                      ^~~
src/main.cpp:30:92: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
   30 |         const auto PLUSMINUSRESULT = getPlusMinusKeywordResult(workspace, ((g_pCompositor->m_lastMonitor->activeWorkspaceID() - 1) % **NUMWORKSPACES) + 1);
      |                                                                                            ^~~~~~~~~~~~~
src/main.cpp:42:100: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
   42 |         const auto PLUSMINUSRESULT = getPlusMinusKeywordResult(workspace.substr(1), g_pCompositor->m_lastMonitor->activeWorkspaceID());
      |                                                                                                    ^~~~~~~~~~~~~
src/main.cpp:61:77: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
   61 |             if (ws->m_isSpecialWorkspace || ws->m_monitor != g_pCompositor->m_lastMonitor)
      |                                                                             ^~~~~~~~~~~~~
src/main.cpp:68:96: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
   68 |         auto findResult = std::ranges::find(validWSes.begin(), validWSes.end(), g_pCompositor->m_lastMonitor->activeWorkspaceID());
      |                                                                                                ^~~~~~~~~~~~~
src/main.cpp:84:52: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
   84 |             const int  id         = g_pCompositor->m_lastMonitor->m_id * (**NUMWORKSPACES) + i;
      |                                                    ^~~~~~~~~~~~~
src/main.cpp:91:9: error: ‘Debug’ has not been declared
   91 |         Debug::log(LOG, "[hyprsplit] no empty workspace on monitor");
      |         ^~~~~
src/main.cpp:91:20: error: ‘LOG’ was not declared in this scope; did you mean ‘Log’?
   91 |         Debug::log(LOG, "[hyprsplit] no empty workspace on monitor");
      |                    ^~~
      |                    Log
src/main.cpp:92:46: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
   92 |         return std::to_string(g_pCompositor->m_lastMonitor->activeWorkspaceID());
      |                                              ^~~~~~~~~~~~~
src/main.cpp:100:42: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
  100 |     return std::to_string(g_pCompositor->m_lastMonitor->m_id * (**NUMWORKSPACES) + wsID);
      |                                          ^~~~~~~~~~~~~
src/main.cpp: In function ‘void ensureGoodWorkspaces()’:
src/main.cpp:118:13: error: ‘Debug’ has not been declared
  118 |             Debug::log(LOG, "[hyprsplit] {} {} active workspace {} out of bounds, changing workspace to {}", m->m_name, m->m_id, m->activeWorkspaceID(), MIN);
      |             ^~~~~
src/main.cpp:118:24: error: ‘LOG’ was not declared in this scope; did you mean ‘Log’?
  118 |             Debug::log(LOG, "[hyprsplit] {} {} active workspace {} out of bounds, changing workspace to {}", m->m_name, m->m_id, m->activeWorkspaceID(), MIN);
      |                        ^~~
      |                        Log
src/main.cpp:143:17: error: ‘Debug’ has not been declared
  143 |                 Debug::log(LOG, "[hyprsplit] workspace {} on monitor {} move to {} {}", ws->m_id, ws->monitorID(), m->m_name, m->m_id);
      |                 ^~~~~
src/main.cpp:143:28: error: ‘LOG’ was not declared in this scope; did you mean ‘Log’?
  143 |                 Debug::log(LOG, "[hyprsplit] workspace {} on monitor {} move to {} {}", ws->m_id, ws->monitorID(), m->m_name, m->m_id);
      |                            ^~~
      |                            Log
src/main.cpp: In function ‘SDispatchResult focusWorkspace(std::string)’:
src/main.cpp:172:46: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
  172 |     const auto PCURRMONITOR = g_pCompositor->m_lastMonitor;
      |                                              ^~~~~~~~~~~~~
src/main.cpp:175:9: error: ‘Debug’ has not been declared
  175 |         Debug::log(ERR, "[hyprsplit] focusWorkspace: monitor doesn't exist");
      |         ^~~~~
src/main.cpp:175:20: error: ‘ERR’ was not declared in this scope; did you mean ‘Log::ERR’?
  175 |         Debug::log(ERR, "[hyprsplit] focusWorkspace: monitor doesn't exist");
      |                    ^~~
      |                    Log::ERR
/var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/plugins/../helpers/../debug/log/Logger.hpp:57:54: note: ‘Log::ERR’ declared here
   57 |     inline constexpr const Hyprutils::CLI::eLogLevel ERR   = Hyprutils::CLI::LOG_ERR;
      |                                                      ^~~
src/main.cpp:182:9: error: ‘Debug’ has not been declared
  182 |         Debug::log(ERR, "[hyprsplit] focusWorkspace: invalid workspace");
      |         ^~~~~
src/main.cpp:182:20: error: ‘ERR’ was not declared in this scope; did you mean ‘Log::ERR’?
  182 |         Debug::log(ERR, "[hyprsplit] focusWorkspace: invalid workspace");
      |                    ^~~
      |                    Log::ERR
/var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/plugins/../helpers/../debug/log/Logger.hpp:57:54: note: ‘Log::ERR’ declared here
   57 |     inline constexpr const Hyprutils::CLI::eLogLevel ERR   = Hyprutils::CLI::LOG_ERR;
      |                                                      ^~~
src/main.cpp:197:9: error: ‘Debug’ has not been declared
  197 |         Debug::log(WARN, "[hyprsplit] focusWorkspace: workspace exists but is on the wrong monitor?");
      |         ^~~~~
src/main.cpp:197:20: error: ‘WARN’ was not declared in this scope; did you mean ‘Log::WARN’?
  197 |         Debug::log(WARN, "[hyprsplit] focusWorkspace: workspace exists but is on the wrong monitor?");
      |                    ^~~~
      |                    Log::WARN
/var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/plugins/../helpers/../debug/log/Logger.hpp:56:54: note: ‘Log::WARN’ declared here
   56 |     inline constexpr const Hyprutils::CLI::eLogLevel WARN  = Hyprutils::CLI::LOG_WARN;
      |                                                      ^~~~
src/main.cpp: In function ‘SDispatchResult swapActiveWorkspaces(std::string)’:
src/main.cpp:308:53: error: ‘class CWorkspace’ has no member named ‘m_prevWorkspace’
  308 |         const auto TMPPREV           = PWORKSPACEA->m_prevWorkspace;
      |                                                     ^~~~~~~~~~~~~~~
src/main.cpp:309:22: error: ‘class CWorkspace’ has no member named ‘m_prevWorkspace’
  309 |         PWORKSPACEA->m_prevWorkspace = PWORKSPACEB->m_prevWorkspace;
      |                      ^~~~~~~~~~~~~~~
src/main.cpp:309:53: error: ‘class CWorkspace’ has no member named ‘m_prevWorkspace’
  309 |         PWORKSPACEA->m_prevWorkspace = PWORKSPACEB->m_prevWorkspace;
      |                                                     ^~~~~~~~~~~~~~~
src/main.cpp:310:22: error: ‘class CWorkspace’ has no member named ‘m_prevWorkspace’
  310 |         PWORKSPACEB->m_prevWorkspace = TMPPREV;
      |                      ^~~~~~~~~~~~~~~
src/main.cpp:316:23: error: ‘class Hyprutils::Memory::CSharedPointer<SDwindleNodeData>’ has no member named ‘workspaceID’
  316 |                 if (n.workspaceID == PWORKSPACEA->m_id)
      |                       ^~~~~~~~~~~
src/main.cpp:317:23: error: ‘class Hyprutils::Memory::CSharedPointer<SDwindleNodeData>’ has no member named ‘workspaceID’
  317 |                     n.workspaceID = PWORKSPACEB->m_id;
      |                       ^~~~~~~~~~~
src/main.cpp:318:28: error: ‘class Hyprutils::Memory::CSharedPointer<SDwindleNodeData>’ has no member named ‘workspaceID’
  318 |                 else if (n.workspaceID == PWORKSPACEB->m_id)
      |                            ^~~~~~~~~~~
src/main.cpp:319:23: error: ‘class Hyprutils::Memory::CSharedPointer<SDwindleNodeData>’ has no member named ‘workspaceID’
  319 |                     n.workspaceID = PWORKSPACEA->m_id;
      |                       ^~~~~~~~~~~
src/main.cpp: In function ‘SDispatchResult grabRogueWindows(std::string)’:
src/main.cpp:385:44: error: ‘class CCompositor’ has no member named ‘m_lastMonitor’
  385 |     const auto PWORKSPACE = g_pCompositor->m_lastMonitor->m_activeWorkspace;
      |                                            ^~~~~~~~~~~~~
src/main.cpp:388:9: error: ‘Debug’ has not been declared
  388 |         Debug::log(ERR, "[hyprsplit] no active workspace?");
      |         ^~~~~
src/main.cpp:388:20: error: ‘ERR’ was not declared in this scope; did you mean ‘Log::ERR’?
  388 |         Debug::log(ERR, "[hyprsplit] no active workspace?");
      |                    ^~~
      |                    Log::ERR
/var/cache/hyprpm/sdooweloc/headersRoot/include/hyprland/src/plugins/../helpers/../debug/log/Logger.hpp:57:54: note: ‘Log::ERR’ declared here
   57 |     inline constexpr const Hyprutils::CLI::eLogLevel ERR   = Hyprutils::CLI::LOG_ERR;
      |                                                      ^~~
src/main.cpp:411:13: error: ‘Debug’ has not been declared
  411 |             Debug::log(LOG, "[hyprsplit] moving window {} to workspace {}", w->m_title, PWORKSPACE->m_id);
      |             ^~~~~
src/main.cpp:411:24: error: ‘LOG’ was not declared in this scope; did you mean ‘Log’?
  411 |             Debug::log(LOG, "[hyprsplit] moving window {} to workspace {}", w->m_title, PWORKSPACE->m_id);
      |                        ^~~
      |                        Log
src/main.cpp: In function ‘void onMonitorAdded(PHLMONITOR)’:
src/main.cpp:420:5: error: ‘Debug’ has not been declared
  420 |     Debug::log(LOG, "[hyprsplit] monitor added {}", pMonitor->m_name);
      |     ^~~~~
src/main.cpp:420:16: error: ‘LOG’ was not declared in this scope; did you mean ‘Log’?
  420 |     Debug::log(LOG, "[hyprsplit] monitor added {}", pMonitor->m_name);
      |                ^~~
      |                Log
src/main.cpp: In function ‘void onMonitorRemoved(PHLMONITOR)’:
src/main.cpp:426:5: error: ‘Debug’ has not been declared
  426 |     Debug::log(LOG, "[hyprsplit] monitor removed {}", pMonitor->m_name);
      |     ^~~~~
src/main.cpp:426:16: error: ‘LOG’ was not declared in this scope; did you mean ‘Log’?
  426 |     Debug::log(LOG, "[hyprsplit] monitor removed {}", pMonitor->m_name);
      |                ^~~
      |                Log
src/main.cpp: In function ‘PLUGIN_DESCRIPTION_INFO pluginInit(void*)’:
src/main.cpp:485:5: error: ‘Debug’ has not been declared
  485 |     Debug::log(LOG, "[hyprsplit] plugin init");
      |     ^~~~~
src/main.cpp:485:16: error: ‘LOG’ was not declared in this scope; did you mean ‘Log’?
  485 |     Debug::log(LOG, "[hyprsplit] plugin init");
      |                ^~~
      |                Log
src/main.cpp: In function ‘void pluginExit()’:
src/main.cpp:490:5: error: ‘Debug’ has not been declared
  490 |     Debug::log(LOG, "[hyprsplit] plugin exit");
      |     ^~~~~
src/main.cpp:490:16: error: ‘LOG’ was not declared in this scope; did you mean ‘Log’?
  490 |     Debug::log(LOG, "[hyprsplit] plugin exit");
      |                ^~~
      |                Log
make: *** [Makefile:7: all] Error 1


✖ Plugin hyprsplit failed to build.
  This likely means that the plugin is either outdated, not yet available for your version, or broken.
  If you are on -git, update first
  Try re-running with -v to see more verbose output.
```

**Comment by sdooweloc** [comment]
wait now it is working? weird but ill close this
